table Medidas
	lineageTag: 21946be0-02be-45e1-8f59-429231c94d7a

	measure 'Faturamento LY' =
			CALCULATE (
			    [Faturamento],
			    SAMEPERIODLASTYEAR ( dCalendario[Data] )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Faturamento/Devoluções
		lineageTag: cc09c598-e86e-48ad-a972-2ffc7185cff8

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Faturamento =
			CALCULATE (
			    SUM ( fVendas[Valor] ),
			    fVendas[Status] = "Venda"
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Faturamento/Devoluções
		lineageTag: 4f0e9801-7fcb-4f35-9e69-8174e0ab6dc4

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Unidades Vendidas' =
			CALCULATE (
			    SUM ( fVendas[Qtde] ),
			    fVendas[Status] = "Venda"
			)
		formatString: #,0
		displayFolder: Faturamento/Devoluções
		lineageTag: 58647c58-6c26-43e3-92fc-11528efb873b

		changedProperty = FormatString

	measure 'Produto Selecionado' =
			"Detalhamento do Veículo "
			    & SELECTEDVALUE ( dProdutos[Produto] )
		displayFolder: Auxiliares
		lineageTag: 599900b2-e13b-4309-9f62-84f9b4df917c

	measure Devoluções =
			CALCULATE (
			    SUM ( fVendas[Valor] ),
			    fVendas[Status] = "Devolução"
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Faturamento/Devoluções
		lineageTag: 7f2dd962-3519-42a7-9836-1914ec9ea025

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Descontos =
			VAR _PrecoBruto =
			    CALCULATE (
			        SUMX (
			            fVendas,
			            fVendas[Qtde]
			                * RELATED ( dProdutos[Preco] )
			        ),
			        fVendas[Status] = "Venda"
			    )
			VAR _PrecoVenda = [Faturamento]
			RETURN
			    _PrecoBruto - _PrecoVenda
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Faturamento/Devoluções
		lineageTag: b7c2a747-5acc-48cd-b6c4-24a3f1af3e4e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Categoria Selecionada' = SELECTEDVALUE ( dProdutos[NomeCategoria] )
		displayFolder: Auxiliares
		lineageTag: 53b10b60-73fe-43e9-a17c-ba1ad592d7d9

	measure Meta = SUM ( fMetas[Meta] )
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metas
		lineageTag: 1b4448fd-8cc5-4c2d-98d1-7088bc3afeb8

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Diferença Meta' = [Meta] - [Faturamento]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metas
		lineageTag: 8b6f4814-9e95-4169-b206-2548e1bec16e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Var % Meta' =
			DIVIDE (
			    [Faturamento] - [Meta],
			    [Faturamento]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Metas
		lineageTag: 4595838e-7c70-40ab-b36f-1333078aafac

		changedProperty = FormatString

	measure Data =
			VAR _MenorMes =
			    MONTH (
			        FIRSTDATE ( dCalendario[Data] )
			    )
			VAR _MenorAno =
			    MIN ( dCalendario[Ano] )
			VAR _AnoSelecionado =
			    SELECTEDVALUE ( dCalendario[Ano] )
			VAR _MesSelecionado =
			    SELECTEDVALUE ( dCalendario[MesAbre] )
			VAR _MenorData =
			    MIN ( dCalendario[Data] )
			VAR _MaiorData =
			    MAX ( dCalendario[Data] )
			RETURN
			    _MenorData & " a " & _MaiorData
		displayFolder: Auxiliares
		lineageTag: e61b398c-3cd6-4085-bef3-f067138c74d0

	measure 'Max Grafico Meta' = [Faturamento] + ( [Faturamento] * 0.5 )
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Auxiliares
		lineageTag: 960db4d2-4cda-4060-a691-6f3b6a981d3e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Formatação Condicional' =
			SWITCH (
			    TRUE (),
			    [Faturamento] >= [Meta], "#00FA9A",
			    "#B22222"
			)
		displayFolder: Auxiliares
		lineageTag: 5d49e3f0-8902-4f3e-b135-ec53446dd6d9

	measure '% Devoluções' =
			DIVIDE (
			    [Devoluções],
			    [Faturamento]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Faturamento/Devoluções
		lineageTag: 186da866-8c5b-4aef-9c6e-cc659872d9a5

		changedProperty = FormatString

	measure 'Faturamento Líquido' = [Faturamento] - [Devoluções]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Faturamento/Devoluções
		lineageTag: f490f4c9-a334-4547-9e36-d441019f5a08

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Em Branco' = ""
		displayFolder: Auxiliares
		lineageTag: 2119905c-e28b-4384-8a65-7ae485a3f55b

	measure IFrame =
			
			"<!DOCTYPE html>
			<html>
			<body>
			<iframe title='CarSales-DesafioDashmaker2 - Página 1' width='1280' height='720' src='https://app.powerbi.com/view?r=eyJrIjoiYTE4YWY2MzItOWJmOS00MTJlLWFlODktYjk3YzU4OTljYzNhIiwidCI6ImMwZTRmYzIyLTk1YWItNDZjZi05YzI4LWZmNWNjMWIxMGYzYyJ9' frameborder='0' allowFullScreen='true'></iframe>
			</body>
			</html>"
		displayFolder: Auxiliares
		lineageTag: 45e3c020-58c3-4e73-9987-06390be79622

	measure 'Dias Úteis' = SUM(dCalendario[Dia útil])
		formatString: 0
		displayFolder: Metas
		lineageTag: da931260-b9d1-4614-83a3-eecbe3847052

	measure 'Meta Diluida' = ```
			
			
			VAR _MetaMensal = 
			CALCULATE(
			    [Meta],
			    ALL(dCalendario),
			    VALUES(dCalendario[MesAno])
			)
			VAR _Dias =
			CALCULATE(
			    [Dias Úteis],
			    ALL(dCalendario),
			    VALUES(dCalendario[MesAno])
			)
			RETURN
			DIVIDE(_MetaMensal,_Dias)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metas
		lineageTag: 47a6e21b-7e8e-4f5c-8c16-2227f4447526

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Pareto Produtos' = ```
			
			VAR _FaturamentoTotal = 
			CALCULATE(
			    [Faturamento],
			    ALLSELECTED(dProdutos[Produto])
			)
			VAR _FaturamentoAtual = [Faturamento]
			Var _Tabela =
			SUMMARIZE(
			    ALLSELECTED(fVendas),
			    dProdutos[Produto],
			    "@Vendas", [Faturamento]
			)
			VAR _FaturamentoAcumulado =
			IF( [Faturamento] > 0,
			SUMX(
			    FILTER(_Tabela, [@Vendas] >= _FaturamentoAtual),
			    [Faturamento]
			)
			)
			RETURN
			DIVIDE(_FaturamentoAcumulado,_FaturamentoTotal)
			    
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Pareto
		lineageTag: fae8d5e2-4203-484c-aa0e-ed776a03d796

		changedProperty = FormatString

	measure 'Faturamento Acumulado' =
			
			VAR _FaturamentoAtual = [Faturamento]
			Var _Tabela =
			SUMMARIZE(
			    ALLSELECTED(fVendas),
			    dProdutos[Produto],
			    "@Vendas", [Faturamento]
			)
			VAR _FaturamentoAcumulado =
			IF( [Faturamento] > 0,
			SUMX(
			    FILTER(_Tabela, [@Vendas] >= _FaturamentoAtual),
			    [Faturamento]
			    )
			)
			RETURN
			_FaturamentoAcumulado
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Pareto
		lineageTag: e2c17572-e573-41f3-830a-258f6a130486

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Classificação ABC' =
			
			IF(ISINSCOPE(dProdutos[Produto]),
			SWITCH(
			    TRUE(),
			    [Pareto Produtos] <= 0.8, "A",
			    [Pareto Produtos] <= 0.9, "B",
			    "C"
			)
			)
		displayFolder: Pareto
		lineageTag: fd39baab-2897-4a17-93cd-d90457b7f4df

	measure 'Cores ABC' =
			
			SWITCH(
			    TRUE(),
			    [Classificação ABC] = "A", "#32CD32",
			    [Classificação ABC] = "B", "#FFD700",
			    [Classificação ABC] = "C", "#DC143C"
			)
		displayFolder: Pareto
		lineageTag: c47f7298-f955-4cd5-91e6-9ca000e3db6a

	measure 'Ranking Produtos' =
			
			RANKX(
			    ALL(dProdutos[Produto]),[Faturamento])
		formatString: 0
		displayFolder: Pareto
		lineageTag: 88aff4c7-49a8-4c36-9a77-21cb59ea83e3

	measure 'Top 5 Produtos Unidades' =
			
			CALCULATE (
			    [Unidades Vendidas],
			    TOPN (
			        5,
			        ALLSELECTED ( dProdutos[Produto] ),
			        [Unidades Vendidas]
			    ),
			    VALUES ( dProdutos[Produto] )
			)
		formatString: #,0
		displayFolder: Auxiliares
		lineageTag: 55ec2838-a7df-4c38-9eb5-a3447338befc

		changedProperty = FormatString

	measure Vendas =
			
			--[Valor] (dProdutos[Segmento] = "Compacto")
			
			/* é a mesma coisa que a Medida Abaixo
			*/
			CALCULATE(
			    [Valor],
			    FILTER(
			        ALL(dProdutos[Segmento]),
			            dProdutos[Segmento] = "Compacto"
			))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: Auxiliares
		lineageTag: 6df187a1-7543-44b1-bfe2-d8b916518211

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Valor = SUM(fVendas[Valor])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Auxiliares
		lineageTag: 0a0a4105-243e-4244-b834-e3f6196e90e2

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Maior Venda' =
			
			VAR _MaiorVenda =
			MAXX(
			    dProdutos,
			    [Faturamento])
			
			VAR _Percentual =
			_MaiorVenda * 0.8
			
			RETURN
			_Percentual
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Auxiliares
		lineageTag: 3b963253-5588-406b-8e92-1e2846572b94

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Verifica Mês Atual' =
			
			IF(MAX(dCalendario[Data])<DATE(YEAR(TODAY()),MONTH(TODAY()),1),1,0)
		formatString: 0
		displayFolder: Auxiliares
		lineageTag: 184661c6-3370-4b8f-a278-685b64d87d61

	measure 'Vendas - Mês Atual' =
			
			CALCULATE(
			    [Faturamento],
			    fVendas[Data] < EOMONTH(MAX(dCalendario[Data]),-1))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Auxiliares
		lineageTag: 238fbb67-d6a5-4b8b-a244-6fd94d19a5ea

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Maior Valor' = MAX(dProdutos[Preco])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Auxiliares
		lineageTag: cdf6e122-d65c-45aa-b636-522009336079

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Maior Produto' = ```
			
			   TOPN(1,ALLSELECTED(dProdutos[Produto]),Medidas[Maior Valor],)
			    
			```
		displayFolder: Auxiliares
		lineageTag: 7fd149e3-5cb9-4de2-9030-23d088681a28

	measure 'Meta Acima' =
			
			IF ([Meta] > [Faturamento],[Meta],BLANK())
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Metas
		lineageTag: 95ab73ae-4783-46ce-97e8-de80ad0ab4da

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Meta Abaixo' =
			
			IF ([Meta] < [Faturamento],[Meta],BLANK())
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metas
		lineageTag: d76f7938-6461-4509-97db-2ff0f1a2c22a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Qtde Produtos acima 80%' =
			
			COUNTROWS(
			    FILTER(
			    VALUES(dProdutos[Produto]),
			    [Fat Acumulado %] <= 0.8)
			)
		formatString: 0
		lineageTag: c96d2129-e95d-4b28-9d3b-ffbef406e2cc

	measure 'Subtitulo Pareto' = ```
			
			[Qtde Produtos acima 80%] & " Produtos representam 80% do Faturamento no total de " & FORMAT([Fatuamento Produtos 80%],"R$ #,#00.00") & 
			UNICHAR(10) & 
			"Qtde A: " & [Qtde Produto A] & "  -  Qtde B: " & [Qtde Produto B] & "  -  Qtde C: " & [Qtde Produto C]  
			```
		lineageTag: e49ee483-94af-4bfe-9b52-c40a0f5a9345

	measure 'Fatuamento Produtos 80%' =
			
			SUMX(
			    FILTER(
			    VALUES(dProdutos[Produto]),
			    [Pareto Produtos] <= 0.8)
			,[Faturamento])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: fcf6d2a2-8225-4cc2-8343-bb3e1dad0ff5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Fat Acumulado SUMX' = ```
			
			VAR _FaturamentoAtual = [Faturamento]
			VAR _Tabela =
			SUMMARIZE(
			    ALLSELECTED(fVendas),
			    dProdutos[Produto],
			    "@Faturamento", [Faturamento]
			)
			VAR _Acumulado = 
			IF( [Faturamento] > 0,
			SUMX(
			    FILTER(_Tabela,[@Faturamento] >= _FaturamentoAtual),
			    [Faturamento]
			))
			RETURN
			_Acumulado
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 43accdf9-55bc-4904-9ff5-309fd2237b1e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Fat Acumulado %' = ```
			
			VAR _FaturamentoAtual = [Faturamento]
			VAR _FaturamentoTotal = 
			CALCULATE(
			    [Faturamento],
			    ALLSELECTED(dProdutos[Produto])
			)
			VAR _Tabela =
			SUMMARIZE(
			    ALLSELECTED(fVendas),
			    dProdutos[Produto],
			    "@Faturamento", [Faturamento]
			)
			VAR _Acumulado = 
			IF( [Faturamento] > 0,
			SUMX(
			    FILTER(_Tabela,[@Faturamento] >= _FaturamentoAtual),
			    [Faturamento]
			))
			RETURN
			_Acumulado / _FaturamentoTotal
			```
		formatString: 0%;-0%;0%
		lineageTag: 1f5bca92-eab7-4d5d-b7d4-69963303cb97

	measure 'Classificação ABC Tabela' =
			
			IF(HASONEFILTER('Classificação'[Coluna 1]),
			IF(SELECTEDVALUE('Classificação'[Coluna 1]) = [Classificação ABC],1,0),1)
		formatString: 0
		lineageTag: 74eac1a7-9384-4adc-90df-e4ffddcb174d

	measure 'Qtd Produtos' = COUNTROWS(dProdutos)
		formatString: #,0
		lineageTag: 40da09d6-eec2-4b60-95c8-917849a4eb37

	measure 'Qtde Produto A' =
			
			COUNTROWS(
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "A"))
		formatString: #,0
		lineageTag: 111ca817-249b-44ba-93b0-21f7e548f631

	measure 'Qtde Produto B' =
			
			COUNTROWS(
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "B"))
		formatString: #,0
		lineageTag: 94a788d5-ba3d-49bb-915d-5282d53a258b

	measure 'Qtde Produto C' =
			
			COUNTROWS(
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "C"))
		formatString: #,0
		lineageTag: e841c4cb-7c39-4cb5-8178-b78aa5fbe1ce

	measure 'Faturamento Produto A' =
			
			CALCULATE(
			    [Faturamento],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "A"))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: d38e36ce-9c9e-42c8-a341-57830fa52cc9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Faturamento Produto B' =
			
			CALCULATE(
			    [Faturamento],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "B"))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f281794b-73fc-4037-99b8-cc794478045e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Faturamento Produto C' =
			
			CALCULATE(
			    [Faturamento],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "C"))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a18ed51b-6303-4b89-bb37-d705d745e5cc

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Grupo A' =
			
			DIVIDE([Faturamento Produto A],[Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 899d9de6-a5b6-463b-98ec-98a796817b34

	measure '% Grupo B' =
			
			DIVIDE([Faturamento Produto B],[Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8225ca28-8c6e-45fa-b2f8-aa5467c9da05

	measure '% Grupo C' =
			
			DIVIDE([Faturamento Produto C],[Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d657db78-bd9e-435d-a274-4ae14c60f35f

	measure 'Ticket Médio' =
			
			DIVIDE([Faturamento],[Unidades Vendidas])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 60684b22-9202-4447-b017-3b6bd9b67a7f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Ticket Médio Grupo A' =
			
			CALCULATE(
			    [Ticket Médio],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "A")
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c4f95f02-4fa1-4240-af67-1366501a2884

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Ticket Médio Grupo B' =
			
			CALCULATE(
			    [Ticket Médio],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "B")
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1d81f0ee-13ac-4f2b-9e26-78dfd2fa9e54

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Ticket Médio Grupo C' =
			
			CALCULATE(
			    [Ticket Médio],
			    FILTER(VALUES(dProdutos[Produto]),
			    [Classificação ABC] = "C")
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: bf5cfe35-513a-42be-ad66-3f83f137407f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Faturamento Acumulado DAX' =
			
			CALCULATE(
			    [Faturamento],
			    DATESYTD(dCalendario[Data])
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: cee1816a-cdce-4f60-a27b-a703da726ca7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Medidas-3a73fa63-5b8a-4611-8622-f613aa54e5c8 = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

